import java.sql.*;
import javax.swing.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * F1INT.java
 *
 * Created on Jan 5, 2014, 8:40:01 AM
 */

/**
 *
 * @author user
 */
public class f1intro extends javax.swing.JFrame {

    /** Creates new form F1INT */
    public f1intro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Presents");
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel2.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel2.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48));
        jTextField1.setForeground(new java.awt.Color(255, 204, 0));
        jTextField1.setText("Present");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 480, 200, 64);

        a1.setBackground(new java.awt.Color(0, 0, 0));
        a1.setEditable(false);
        a1.setFont(new java.awt.Font("Footlight MT Light", 1, 100)); // NOI18N
        a1.setForeground(new java.awt.Color(153, 51, 0));
        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.setText("Gaurav & Vishal");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        a1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a1FocusGained(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(-30, -10, 1430, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a1ActionPerformed

    private void a1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusGained
    try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            String sql2="select sleep(2);";
            s.executeQuery(sql2);
            con.close();
            s.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}
     dispose();
     new f2intro().setVisible(true);
    
// TODO add your handling code here:
}//GEN-LAST:event_a1FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
