import java.sql.*;
import javax.swing.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f2intro.java
 *
 * Created on Jan 28, 2014, 11:40:26 AM
 */

/**
 *
 * @author student
 */
public class f2intro extends javax.swing.JFrame {

    /** Creates new form f2intro */
    public f2intro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a3 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        a3.setFont(new java.awt.Font("SimHei", 1, 48));
        a3.setForeground(new java.awt.Color(153, 0, 51));
        a3.setText("Master Piece");
        a3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                a3MouseMoved(evt);
            }
        });
        a3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a3FocusGained(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(30, 220, 324, 56);

        a2.setFont(new java.awt.Font("SimHei", 1, 36));
        a2.setForeground(new java.awt.Color(153, 0, 51));
        a2.setText("The");
        getContentPane().add(a2);
        a2.setBounds(130, 180, 60, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back/Blue-Eyes-White-Dragon-yu-gi-oh-17179629-1280-800.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1026, 767));
        jLabel2.setMinimumSize(new java.awt.Dimension(1026, 767));
        jLabel2.setPreferredSize(new java.awt.Dimension(1026, 767));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1280, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseMoved
        dispose();
        new f4menu().setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_a3MouseMoved

    private void a3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a3FocusGained
       // TODO add your handling code here:
}//GEN-LAST:event_a3FocusGained

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusGained

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
 try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            String sql2="select sleep(2);";
            s.executeQuery(sql2);
            con.close();
            s.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}
        dispose();
        new f4menu().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f2intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
