import java.sql.*;
import javax.swing.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f4menu.java
 *
 * Created on Jan 5, 2014, 9:50:54 AM
 */

/**
 *
 * @author user
 */
public class f4menu extends javax.swing.JFrame {

    /** Creates new form f4menu */
    public f4menu() {
        initComponents();
        a2.setVisible(false);
        a3.setVisible(false);

        a5.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JButton();
        dere = new javax.swing.JButton();
        dere2 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        a1.setFont(new java.awt.Font("Footlight MT Light", 1, 48));
        a1.setForeground(new java.awt.Color(153, 0, 102));
        a1.setText("New Game");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(140, 60, 490, 70);

        dere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back/bback1.jpg"))); // NOI18N
        dere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dereActionPerformed(evt);
            }
        });
        getContentPane().add(dere);
        dere.setBounds(50, 60, 70, 70);

        dere2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back/nnext1.jpg"))); // NOI18N
        dere2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dere2ActionPerformed(evt);
            }
        });
        getContentPane().add(dere2);
        dere2.setBounds(650, 60, 70, 70);

        a2.setFont(new java.awt.Font("Footlight MT Light", 1, 48));
        a2.setForeground(new java.awt.Color(153, 0, 102));
        a2.setText("Statistics");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(140, 60, 490, 70);

        a3.setFont(new java.awt.Font("Footlight MT Light", 1, 48));
        a3.setForeground(new java.awt.Color(153, 0, 102));
        a3.setText("Player Enroller");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(140, 60, 490, 70);

        a5.setFont(new java.awt.Font("Footlight MT Light", 1, 48));
        a5.setForeground(new java.awt.Color(153, 0, 102));
        a5.setText("Exit");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        getContentPane().add(a5);
        a5.setBounds(140, 60, 490, 70);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 0, 840);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YU GI OH/logo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 500, 300, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/YU GI OH/yu-gi-oh-monster-master.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 651));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
       dispose();
new f5gameplay().setVisible(true); // TODO add your handling code here:
}//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
dispose();
new f5playerstats().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
dispose();
new f5playerenroller().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
dispose();
      // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void dere2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dere2ActionPerformed
        if (a1.isVisible()==true){a2.setVisible(true);
        a1.setVisible(false); }
        else if (a2.isVisible()==true){a3.setVisible(true);
        a2.setVisible(false); }
         else if (a3.isVisible()==true){a5.setVisible(true);
        a3.setVisible(false); }
       
         else if (a5.isVisible()==true){a1.setVisible(true);
        a5.setVisible(false); }
              // TODO add your handling code here:
    }//GEN-LAST:event_dere2ActionPerformed

    private void dereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dereActionPerformed
    if (a1.isVisible()==true){a5.setVisible(true);
        a1.setVisible(false); }
        else if (a2.isVisible()==true){a1.setVisible(true);
        a2.setVisible(false); }
         else if (a3.isVisible()==true){a2.setVisible(true);
        a3.setVisible(false); }
       
         else if (a5.isVisible()==true){a3.setVisible(true);
        a5.setVisible(false); }        // TODO add your handling code here:
    }//GEN-LAST:event_dereActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f4menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a5;
    private javax.swing.JButton dere;
    private javax.swing.JButton dere2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
