import java.sql.*;

import javax.swing.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * f5gameplay.java
 *
 * Created on Jan 28, 2014, 8:06:17 PM
 */

/**
 *
 * @author student
 */
public class f5gameplay extends javax.swing.JFrame {

    /** Creates new form f5gameplay */
    public f5gameplay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yop = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        p2 = new javax.swing.JPasswordField();
        l1 = new javax.swing.JLabel();
        pro1 = new javax.swing.JButton();
        back = new javax.swing.JToggleButton();
        p1 = new javax.swing.JPasswordField();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        b2 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1300, 700));

        yop.setFont(new java.awt.Font("Andalus", 1, 36));
        yop.setForeground(new java.awt.Color(51, 102, 0));
        yop.setText("Enter password");
        yop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yopFocusGained(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 36));
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });

        p2.setForeground(new java.awt.Color(51, 102, 0));
        p2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                p2CaretUpdate(evt);
            }
        });
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 51, 51));

        pro1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        pro1.setForeground(new java.awt.Color(0, 0, 102));
        pro1.setText("Proceed");
        pro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro1ActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        back.setForeground(new java.awt.Color(51, 0, 102));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        p1.setForeground(new java.awt.Color(51, 102, 0));
        p1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                p1CaretUpdate(evt);
            }
        });
        p1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                p1PropertyChange(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        cb1.setForeground(new java.awt.Color(51, 102, 0));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        cb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb1FocusGained(evt);
            }
        });
        cb1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb1PropertyChange(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        cb2.setForeground(new java.awt.Color(51, 102, 0));
        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });

        l2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        l2.setForeground(new java.awt.Color(255, 51, 51));

        d1.setEnabled(false);
        d1.setFocusable(false);
        d1.setInheritsPopupMenu(false);

        d2.setEnabled(false);
        d2.setFocusable(false);
        d2.setInheritsPopupMenu(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(611, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(549, 549, 549))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addComponent(pro1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 25, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(yop, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(p1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 25, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 650, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(d1)
                        .addComponent(d2))
                    .addGap(0, 650, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(pro1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(yop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 350, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(d1)
                        .addComponent(d2))
                    .addGap(0, 350, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yopFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yopFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_yopFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultComboBoxModel cb11 =(DefaultComboBoxModel)cb1.getModel();
        Object abc1 =cb1.getSelectedItem();
        String sd1 =""+abc1;
        DefaultComboBoxModel cb22 =(DefaultComboBoxModel)cb2.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();

            String sql="select name from player ;";
            ResultSet rs = s.executeQuery(sql);
            while (rs.next()) {
                String s_no = rs.getString(1);
                cb11.addElement(s_no);
                cb1.setModel(cb11);
            }
            rs.close();
            s.close();
            con.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}
        Object abc =cb2.getSelectedItem();
        String sd =""+abc;

        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();

            String sql="select name from player ;";
            ResultSet rs = s.executeQuery(sql);
            while (rs.next()) {
                String s_no = rs.getString(1);
                cb22.addElement(s_no);
                cb2.setModel(cb22);
            }
            rs.close();
            s.close();
            con.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}
       
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n1 =cb1.getSelectedItem();
            String n11 =""+n1;
            Object n2 =cb2.getSelectedItem();
            String n12 =""+n2;
            if( !(n11.isEmpty()==true && n12.isEmpty()==true)){
                String sql=" drop table playerexecutive ;";
                String sql1="create table playerexecutive (name char(100)); ";
                String sql11=       "insert into playerexecutive values ('"+n11+"');"+"insert into playerexecutive values ('"+n12+"');";
                s.executeUpdate(sql);
                s.executeUpdate(sql1);
                s.executeUpdate(sql11);}
            s.close();
            con.close();
        } catch (Exception e){}
        // TODO add your handling code here:*/
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        d1.setVisible(false);
        d2.setVisible(false);  // TODO add your handling code here:
}//GEN-LAST:event_jButton1FocusGained

    private void p2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_p2CaretUpdate
        try{ String ss1="",ss2="";
        Class.forName("java.sql.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
        Statement s = con.createStatement();
        Object n1 =cb1.getSelectedItem();
        String n11 =""+n1;
        Object n2 =cb2.getSelectedItem();
        String n12 =""+n2;
        String sql="select password from player where name ='"+n12+"';";

        ResultSet rs = s.executeQuery(sql);
        while (rs.next())
            ss1 = rs.getString(1);






        rs.close();

        s.close();
        con.close();
        d2.setText(p2.getText());

        if (ss1.equals(d2.getText()) ){d2.setText("q");
        l2.setText("correct password");} else l2.setText("incorrect password");



        if (l2.getText().equals("correct password"))
            pro1.setEnabled(true);
        else pro1.setEnabled(false);
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}  // TODO add your handling code here:
}//GEN-LAST:event_p2CaretUpdate

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_p2ActionPerformed

    private void pro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro1ActionPerformed
if(p1.getText().equals("")||p1.getText().equals("")){JOptionPane.showMessageDialog(this, "enter password");}
else{
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n1 =cb1.getSelectedItem();
            String n11 =""+n1;
            Object n2 =cb2.getSelectedItem();
            String n12 =""+n2;

            String sql=" drop table playerexecutive ;";
            s.executeUpdate(sql);

            s.close();
            con.close();
        } catch (Exception e){;}


        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n1 =cb1.getSelectedItem();
            String n11 =""+n1;
            Object n2 =cb2.getSelectedItem();
            String n12 =""+n2;

            String sql1="create table playerexecutive (name char(100)); ";
            s.executeUpdate(sql1);
            s.close();
            con.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}


        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n1 =cb1.getSelectedItem();
            String n11 =""+n1;
            Object n2 =cb2.getSelectedItem();
            String n12 =""+n2;

            String sql11= "insert into playerexecutive values ('"+n11+"');";
            String sql12="insert into playerexecutive values ('"+n12+"');";
            s.executeUpdate(sql11);
            s.executeUpdate(sql12);
            s.close();
            con.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}



        dispose();
        new f6showdown().setVisible(true);}


        // TODO add your handling code here:
}//GEN-LAST:event_pro1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        dispose();
        new f4menu().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_backActionPerformed

    private void p1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_p1CaretUpdate
        try{ String ss1="",ss2="";
        Class.forName("java.sql.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
        Statement s = con.createStatement();
        Object n1 =cb1.getSelectedItem();
        String n11 =""+n1;
        Object n2 =cb2.getSelectedItem();
        String n12 =""+n2;
        String sql="select password from player where name ='"+n11+"';";

        ResultSet rs = s.executeQuery(sql);
        while (rs.next())
            ss1 = rs.getString(1);






        rs.close();

        s.close();
        con.close();
        d1.setText(p1.getText());

        if (ss1.equals(d1.getText()) ){d1.setText("q");
        l1.setText("correct password");} else l1.setText("incorrect password");



        if (l2.getText().equals("correct password"))
            pro1.setEnabled(true);
        else pro1.setEnabled(false);
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}            // TODO add your handling code here:
}//GEN-LAST:event_p1CaretUpdate

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
     Object nw1 =cb1.getSelectedItem();
   Object nw2 =cb2.getSelectedItem();
        String sd,tryy1=""+nw1,tryy2=""+nw2;

        if(!(tryy1.equals(""))){

if(!(tryy2.equals(""))){
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n1 =cb1.getSelectedItem();

            String sql="select imageid from player where name ='"+n1+"';";

            ResultSet rs = s.executeQuery(sql);

            rs.first();
            sd =rs.getString(1);

            String hg =sd.substring(1,4);

            switch (Integer.parseInt(hg)){

                    case 0:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c000.jpg"))); break;

                    case 1:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c001.jpg"))); break;

                    case 2:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c002.gif"))); break;

                    case 3:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c003.jpg"))); break;

                    case 4:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c004.jpg"))); break;

                    case 5:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c005.gif"))); break;

                    case 6:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c006.jpg"))); break;

                    case 7:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c007.jpg"))); break;

                    case 8:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c008.jpg"))); break;

                    case 9:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c009.jpg"))); break;

                    case 10:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c010.jpg"))); break;

                    case 11:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c011.jpg"))); break;

                    case 12:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c012.jpg"))); break;

                    case 13:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c013.jpg"))); break;

                    case 14:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c014.jpg"))); break;

                    case 15:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c015.jpg"))); break;

                    case 16:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c016.jpg"))); break;

                    case 17:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c017.gif"))); break;

                    case 18:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c018.jpg"))); break;

                    case 19:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c019.gif"))); break;

                    case 20:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c020.jpg"))); break;

                    case 21:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c021.gif"))); break;

                    case 22:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c022.jpg"))); break;

                    case 23:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c023.gif"))); break;

                    case 24:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c024.jpg"))); break;

                    case 25:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c025.jpg"))); break;

                    case 26:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c026.gif"))); break;

                    case 27:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c027.gif"))); break;

                    case 28:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c028.jpg"))); break;

                    case 29:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c029.jpg"))); break;

                    case 30:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c030.gif"))); break;

                    case 31:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c031.gif"))); break;

                    case 32:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c032.jpg"))); break;

                    case 33:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c033.jpg"))); break;

                    case 34:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c034.jpg"))); break;

                    case 35:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c035.jpg"))); break;

                    case 36:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c036.jpg"))); break;

                    case 37:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c037.jpg"))); break;

                    case 38:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c038.jpg"))); break;

                    case 39:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c039.jpg"))); break;

                    case 40:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c040.jpg"))); break;

                    case 41:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c041.jpg"))); break;

                    case 42:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c042.jpg"))); break;

                    case 43:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c043.jpg"))); break;

                    case 44:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c044.jpg"))); break;

                    case 45:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c045.jpg"))); break;

                    case 46:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c046.jpg"))); break;

                    case 47:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c047.jpg"))); break;

                    case 48:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c048.jpg"))); break;

                    case 49:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c049.jpg"))); break;

                    case 50:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c050.jpg"))); break;

                    case 51:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c051.jpg"))); break;

                    case 52:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c052.jpg"))); break;

                    case 53:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c053.jpg"))); break;

                    case 54:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c054.jpg"))); break;

                    case 55:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c055.jpg"))); break;

                    case 56:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c056.jpg"))); break;

                    case 57:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c057.jpg"))); break;

                    case 58:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c058.jpg"))); break;

                    case 59:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c059.jpg"))); break;

                    case 60:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c060.jpg"))); break;

                    case 61:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c061.jpg"))); break;

                    case 62:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c062.gif"))); break;

                    case 63:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c063.jpg"))); break;

                    case 64:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c064.gif"))); break;

                    case 65:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c065.jpg"))); break;

                    case 66:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c066.jpg"))); break;

                    case 67:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c067.jpg"))); break;

                    case 68:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c068.jpg"))); break;

                    case 69:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c069.jpg"))); break;

                    case 70:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c070.jpg"))); break;

                    case 71:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c071.jpg"))); break;

                    case 72:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c072.jpg"))); break;

                    case 73:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c073.gif"))); break;

                    case 74:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c074.jpg"))); break;

                    case 75:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c075.jpg"))); break;

                    case 76:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c076.jpg"))); break;

                    case 77:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c077.jpg"))); break;

                    case 78:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c078.jpg"))); break;

                    case 79:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c079.jpg"))); break;

                    case 80:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c080.jpg"))); break;

                    case 81:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c081.jpg"))); break;

                    case 82:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c082.jpg"))); break;

                    case 83:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c083.jpg"))); break;

                    case 84:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c084.jpg"))); break;

                    case 85:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c085.jpg"))); break;

                    case 86:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c086.jpg"))); break;

                    case 87:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c087.jpg"))); break;

                    case 88:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c088.jpg"))); break;

                    case 89:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c089.jpg"))); break;

                    case 90:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c090.jpg"))); break;

                    case 91:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c091.jpg"))); break;
                    case 92:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c092.jpg"))); break;

                    case 93:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c093.jpg"))); break;

                    case 94:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c094.jpg"))); break;

                    case 95:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c095.jpg"))); break;

                    case 96:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c096.jpg"))); break;

                    case 97:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c097.jpg"))); break;

                    case 98:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c098.jpg"))); break;

                    case 99:b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c099.jpg"))); break;



            }
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}

        }//if
else{b2.setText("PLAYER 2");}
        }//if
        else{b1.setText("PLAYER 1");}   // TODO add your handling code here:
}//GEN-LAST:event_cb1ItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cb1ActionPerformed

    private void cb1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb1FocusGained
        d1.setVisible(false);
        d2.setVisible(false);      // TODO add your handling code here:
}//GEN-LAST:event_cb1FocusGained

    private void cb1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb1PropertyChange
// TODO add your handling code here:
    }//GEN-LAST:event_cb1PropertyChange

    private void p1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_p1PropertyChange
       // TODO add your handling code here:
    }//GEN-LAST:event_p1PropertyChange

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
       Object nw1 =cb1.getSelectedItem();
   Object nw2 =cb2.getSelectedItem();
        String sd,tryy1=""+nw1,tryy2=""+nw2;

        if(!(tryy1.equals(""))){

if(!(tryy2.equals(""))){
        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            Object n2 =cb2.getSelectedItem();

            String sql="select imageid from player where name ='"+n2+"';";

            ResultSet rs = s.executeQuery(sql);

            rs.first();
            sd =rs.getString(1);

            String hg =sd.substring(1,4);

            switch (Integer.parseInt(hg)){


              

                    case 1:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c001.jpg"))); break;

                    case 2:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c002.gif"))); break;

                    case 3:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c003.jpg"))); break;

                    case 4:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c004.jpg"))); break;

                    case 5:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c005.gif"))); break;

                    case 6:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c006.jpg"))); break;

                    case 7:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c007.jpg"))); break;

                    case 8:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c008.jpg"))); break;

                    case 9:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c009.jpg"))); break;

                    case 10:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c010.jpg"))); break;

                    case 11:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c011.jpg"))); break;

                    case 12:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c012.jpg"))); break;

                    case 13:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c013.jpg"))); break;

                    case 14:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c014.jpg"))); break;

                    case 15:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c015.jpg"))); break;

                    case 16:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c016.jpg"))); break;

                    case 17:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c017.gif"))); break;

                    case 18:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c018.jpg"))); break;

                    case 19:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c019.gif"))); break;

                    case 20:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c020.jpg"))); break;

                    case 21:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c021.gif"))); break;

                    case 22:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c022.jpg"))); break;

                    case 23:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c023.gif"))); break;

                    case 24:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c024.jpg"))); break;

                    case 25:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c025.jpg"))); break;

                    case 26:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c026.gif"))); break;

                    case 27:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c027.gif"))); break;

                    case 28:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c028.jpg"))); break;

                    case 29:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c029.jpg"))); break;

                    case 30:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c030.gif"))); break;

                    case 31:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c031.gif"))); break;

                    case 32:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c032.jpg"))); break;

                    case 33:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c033.jpg"))); break;

                    case 34:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c034.jpg"))); break;

                    case 35:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c035.jpg"))); break;

                    case 36:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c036.jpg"))); break;

                    case 37:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c037.jpg"))); break;

                    case 38:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c038.jpg"))); break;

                    case 39:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c039.jpg"))); break;

                    case 40:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c040.jpg"))); break;

                    case 41:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c041.jpg"))); break;

                    case 42:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c042.jpg"))); break;

                    case 43:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c043.jpg"))); break;

                    case 44:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c044.jpg"))); break;

                    case 45:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c045.jpg"))); break;

                    case 46:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c046.jpg"))); break;

                    case 47:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c047.jpg"))); break;

                    case 48:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c048.jpg"))); break;

                    case 49:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c049.jpg"))); break;

                    case 50:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c050.jpg"))); break;

                    case 51:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c051.jpg"))); break;

                    case 52:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c052.jpg"))); break;

                    case 53:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c053.jpg"))); break;

                    case 54:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c054.jpg"))); break;

                    case 55:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c055.jpg"))); break;

                    case 56:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c056.jpg"))); break;

                    case 57:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c057.jpg"))); break;

                    case 58:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c058.jpg"))); break;

                    case 59:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c059.jpg"))); break;

                    case 60:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c060.jpg"))); break;

                    case 61:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c061.jpg"))); break;

                    case 62:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c062.gif"))); break;

                    case 63:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c063.jpg"))); break;

                    case 64:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c064.gif"))); break;

                    case 65:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c065.jpg"))); break;

                    case 66:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c066.jpg"))); break;

                    case 67:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c067.jpg"))); break;

                    case 68:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c068.jpg"))); break;

                    case 69:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c069.jpg"))); break;

                    case 70:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c070.jpg"))); break;

                    case 71:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c071.jpg"))); break;

                    case 72:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c072.jpg"))); break;

                    case 73:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c073.gif"))); break;

                    case 74:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c074.jpg"))); break;

                    case 75:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c075.jpg"))); break;

                    case 76:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c076.jpg"))); break;

                    case 77:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c077.jpg"))); break;

                    case 78:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c078.jpg"))); break;

                    case 79:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c079.jpg"))); break;

                    case 80:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c080.jpg"))); break;

                    case 81:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c081.jpg"))); break;

                    case 82:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c082.jpg"))); break;

                    case 83:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c083.jpg"))); break;

                    case 84:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c084.jpg"))); break;

                    case 85:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c085.jpg"))); break;

                    case 86:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c086.jpg"))); break;

                    case 87:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c087.jpg"))); break;

                    case 88:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c088.jpg"))); break;

                    case 89:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c089.jpg"))); break;

                    case 90:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c090.jpg"))); break;

                    case 91:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c091.jpg"))); break;
                    case 92:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c092.jpg"))); break;

                    case 93:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c093.jpg"))); break;

                    case 94:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c094.jpg"))); break;

                    case 95:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c095.jpg"))); break;

                    case 96:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c096.jpg"))); break;

                    case 97:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c097.jpg"))); break;

                    case 98:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c098.jpg"))); break;

                    case 99:b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c099.jpg"))); break;





            }
        } catch (Exception e){JOptionPane.showMessageDialog(this, e);}

        }//if
else{b2.setText("PLAYER 2");}
        }//if
        else{b1.setText("PLAYER 1");}    // TODO add your handling code here:
    }//GEN-LAST:event_cb2ItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f5gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JToggleButton back;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JButton pro1;
    private javax.swing.JLabel yop;
    // End of variables declaration//GEN-END:variables

}
