import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * playerstats.java
 *
 * Created on Dec 20, 2013, 1:41:14 AM
 */

/**
 *
 * @author user
 */
public class f5playerstats extends javax.swing.JFrame {

    /** Creates new form playerstats */
    public f5playerstats() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        a3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.setFont(new java.awt.Font("Algerian", 1, 48));
        b2.setForeground(new java.awt.Color(102, 0, 51));
        b2.setText("back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b2FocusGained(evt);
            }
        });

        tb1.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        tb1.setForeground(new java.awt.Color(0, 51, 51));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "points", "total matches", "win", "lost"
            }
        ));
        tb1.setRowHeight(35);
        tb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        a3.setFont(new java.awt.Font("Segoe Script", 1, 150));
        a3.setForeground(new java.awt.Color(102, 102, 0));
        a3.setText("player statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1349, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 1311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 1333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
dispose();
new f4menu().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b2FocusGained
   
    }//GEN-LAST:event_b2FocusGained

    private void tb1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb1FocusGained
    DefaultTableModel tb=(DefaultTableModel)tb1.getModel();

        tb.setRowCount(0);
        String sql="select name ,points,totalmatches,win,lost from player order by points desc ;";
        try
 {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","")  ;
            Statement s=con.createStatement();
            ResultSet rs=s.executeQuery(sql);

            while(rs.next()) {

                String a=rs.getString(1);
                String b=rs.getString(2);
                String c=rs.getString(3);
                String d=rs.getString(4);
                String e=rs.getString(5);


                tb.addRow(new Object[]{a,b,c,d,e,});
            }
            rs.close();
            s.close();
            con.close();
        }
   catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_tb1FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f5playerstats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a3;
    private javax.swing.JToggleButton b2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
