import java.security.SecureRandom;
import java.sql.*;
import java.util.Random;
import javax.swing.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * playerenroller.java
 *
 * Created on Jan 5, 2014, 11:27:11 AM
 */

/**
 *
 * @author user
 */
public class f5playerenroller extends javax.swing.JFrame {
Connection con123 ;
Statement s123;
ResultSet rs123;
String sql123;
    /** Creates new form playerenroller */
    public f5playerenroller() {
        initComponents();

tt1.setVisible(false);
        try{
            Class.forName("java.sql.Driver");
            Connection con123= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s123 = con123.createStatement();


         sql123="select id from charactar ;";


         rs123=   s123.executeQuery(sql123);


           } catch (Exception e){JOptionPane.showMessageDialog(this, e);}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tt1 = new javax.swing.JTextArea();
        top = new javax.swing.JLabel();
        top12334 = new javax.swing.JLabel();
        b2 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        img1 = new javax.swing.JButton();
        ifitis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        a4 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();

        tt1.setColumns(20);
        tt1.setRows(5);
        jScrollPane2.setViewportView(tt1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        top.setFont(new java.awt.Font("Agency FB", 1, 36));
        top.setText("select your image");
        top.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                topFocusGained(evt);
            }
        });
        getContentPane().add(top);
        top.setBounds(900, 10, 220, 40);

        top12334.setBackground(new java.awt.Color(204, 204, 0));
        top12334.setFont(new java.awt.Font("Jokerman", 1, 36));
        top12334.setForeground(new java.awt.Color(0, 102, 102));
        top12334.setText("ENTER   INFORMATION");
        top12334.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top12334FocusGained(evt);
            }
        });
        getContentPane().add(top12334);
        top12334.setBounds(60, 10, 580, 60);

        b2.setFont(new java.awt.Font("Segoe Print", 1, 30));
        b2.setForeground(new java.awt.Color(0, 0, 255));
        b2.setText("menu");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                b2FocusGained(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(570, 490, 160, 120);

        jButton4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 48));
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("previous");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 530, 260, 90);

        jButton5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 48));
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1060, 530, 230, 90);

        img1.setFont(new java.awt.Font("Andalus", 0, 24));
        img1.setText("c001");
        getContentPane().add(img1);
        img1.setBounds(750, 10, 140, 50);

        ifitis.setFont(new java.awt.Font("Andalus", 0, 24));
        ifitis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifitisActionPerformed(evt);
            }
        });
        getContentPane().add(ifitis);
        ifitis.setBounds(1130, 10, 140, 50);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText(" name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 240, 100);

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("pasword");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 220, 250, 100);

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 1, 36));
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("starting points");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 340, 260, 100);

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 30));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("prepare deck");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 490, 250, 120);

        a4.setEditable(false);
        a4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        a4.setForeground(new java.awt.Color(102, 102, 0));
        a4.setText("1000");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        getContentPane().add(a4);
        a4.setBounds(360, 340, 360, 100);

        a1.setFont(new java.awt.Font("Times New Roman", 0, 48));
        a1.setForeground(new java.awt.Color(102, 102, 0));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(360, 100, 360, 90);

        a3.setFont(new java.awt.Font("Times New Roman", 0, 48));
        a3.setForeground(new java.awt.Color(102, 102, 0));
        getContentPane().add(a3);
        a3.setBounds(360, 220, 360, 100);

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 30));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("get enrolled");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 490, 270, 120);

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c001.jpg"))); // NOI18N
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12);
        b12.setBounds(740, 70, 530, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        dispose();
        new f4menu().setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_b2ActionPerformed

    private void b2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_b2FocusGained
        try {
            String sql1 = "select used from charactar where id ='"+img1.getText()+"' ;";
            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s1 = con1.createStatement();
            ResultSet rs1 = null;

            rs1 = s1.executeQuery(sql1);
            rs1.next();

            String aa1 = null;

            aa1 = rs1.getString("used");


            if (aa1.equals("yes")){ifitis.setText(" in use");} else ifitis.setText("not in use");

            con1.close();
            s1.close();

        } catch (Exception e){JOptionPane.showMessageDialog(this, e);
        }       // TODO add your handling code here:
}//GEN-LAST:event_b2FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String ew="c002";
        try {
            if(rs123.previous()){
                ew=rs123.getString(1);
                img1.setText(ew);

                String hg= ew.substring(1, 4);
                switch (Integer.parseInt(hg)){

                    case 0:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c000.jpg"))); break;

                    case 1:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c001.jpg"))); break;

                    case 2:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c002.gif"))); break;

                    case 3:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c003.jpg"))); break;

                    case 4:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c004.jpg"))); break;

                    case 5:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c005.gif"))); break;

                    case 6:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c006.jpg"))); break;

                    case 7:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c007.jpg"))); break;

                    case 8:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c008.jpg"))); break;

                    case 9:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c009.jpg"))); break;

                    case 10:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c010.jpg"))); break;

                    case 11:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c011.jpg"))); break;

                    case 12:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c012.jpg"))); break;

                    case 13:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c013.jpg"))); break;

                    case 14:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c014.jpg"))); break;

                    case 15:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c015.jpg"))); break;

                    case 16:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c016.jpg"))); break;

                    case 17:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c017.gif"))); break;

                    case 18:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c018.jpg"))); break;

                    case 19:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c019.gif"))); break;

                    case 20:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c020.jpg"))); break;

                    case 21:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c021.gif"))); break;

                    case 22:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c022.jpg"))); break;

                    case 23:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c023.gif"))); break;

                    case 24:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c024.jpg"))); break;

                    case 25:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c025.jpg"))); break;

                    case 26:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c026.gif"))); break;

                    case 27:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c027.gif"))); break;

                    case 28:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c028.jpg"))); break;

                    case 29:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c029.jpg"))); break;

                    case 30:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c030.gif"))); break;

                    case 31:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c031.gif"))); break;

                    case 32:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c032.jpg"))); break;

                    case 33:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c033.jpg"))); break;

                    case 34:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c034.jpg"))); break;

                    case 35:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c035.jpg"))); break;

                    case 36:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c036.jpg"))); break;

                    case 37:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c037.jpg"))); break;

                    case 38:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c038.jpg"))); break;

                    case 39:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c039.jpg"))); break;

                    case 40:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c040.jpg"))); break;

                    case 41:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c041.jpg"))); break;

                    case 42:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c042.jpg"))); break;

                    case 43:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c043.jpg"))); break;

                    case 44:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c044.jpg"))); break;

                    case 45:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c045.jpg"))); break;

                    case 46:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c046.jpg"))); break;

                    case 47:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c047.jpg"))); break;

                    case 48:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c048.jpg"))); break;

                    case 49:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c049.jpg"))); break;

                    case 50:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c050.jpg"))); break;

                    case 51:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c051.jpg"))); break;

                    case 52:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c052.jpg"))); break;

                    case 53:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c053.jpg"))); break;

                    case 54:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c054.jpg"))); break;

                    case 55:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c055.jpg"))); break;

                    case 56:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c056.jpg"))); break;

                    case 57:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c057.jpg"))); break;

                    case 58:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c058.jpg"))); break;

                    case 59:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c059.jpg"))); break;

                    case 60:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c060.jpg"))); break;

                    case 61:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c061.jpg"))); break;

                    case 62:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c062.gif"))); break;

                    case 63:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c063.jpg"))); break;

                    case 64:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c064.gif"))); break;

                    case 65:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c065.jpg"))); break;

                    case 66:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c066.jpg"))); break;

                    case 67:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c067.jpg"))); break;

                    case 68:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c068.jpg"))); break;

                    case 69:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c069.jpg"))); break;

                    case 70:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c070.jpg"))); break;

                    case 71:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c071.jpg"))); break;

                    case 72:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c072.jpg"))); break;

                    case 73:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c073.gif"))); break;

                    case 74:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c074.jpg"))); break;

                    case 75:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c075.jpg"))); break;

                    case 76:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c076.jpg"))); break;

                    case 77:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c077.jpg"))); break;

                    case 78:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c078.jpg"))); break;

                    case 79:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c079.jpg"))); break;

                    case 80:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c080.jpg"))); break;

                    case 81:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c081.jpg"))); break;

                    case 82:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c082.jpg"))); break;

                    case 83:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c083.jpg"))); break;

                    case 84:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c084.jpg"))); break;

                    case 85:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c085.jpg"))); break;

                    case 86:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c086.jpg"))); break;

                    case 87:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c087.jpg"))); break;

                    case 88:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c088.jpg"))); break;

                    case 89:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c089.jpg"))); break;

                    case 90:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c090.jpg"))); break;

                    case 91:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c091.jpg"))); break;
                    case 92:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c092.jpg"))); break;

                    case 93:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c093.jpg"))); break;

                    case 94:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c094.jpg"))); break;

                    case 95:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c095.jpg"))); break;

                    case 96:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c096.jpg"))); break;

                    case 97:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c097.jpg"))); break;

                    case 98:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c098.jpg"))); break;

                    case 99:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c099.jpg"))); break;



                }


            } else {JOptionPane.showMessageDialog(this,"last reached");}
        } catch (Exception e){
        }

        try {
            String sql1 = "select used from charactar where id ='"+img1.getText()+"' ;";

            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s1 = con1.createStatement();
            ResultSet rs1 = null;

            rs1 = s1.executeQuery(sql1);
            rs1.next();

            String aa1 = null;

            aa1 = rs1.getString("used");


            if (aa1.equals("yes")){ifitis.setText(" in use");} else ifitis.setText("not in use");

            con1.close();
            s1.close();

        } catch (Exception e){JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String ew="c001";
        try {
            if(rs123.next()){
                ew=rs123.getString(1);
                img1.setText(ew);

                String hg= ew.substring(1, 4);
                switch (Integer.parseInt(hg)){
case 0:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c000.jpg"))); break;

                    case 1:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c001.jpg"))); break;

                    case 2:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c002.gif"))); break;

                    case 3:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c003.jpg"))); break;

                    case 4:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c004.jpg"))); break;

                    case 5:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c005.gif"))); break;

                    case 6:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c006.jpg"))); break;

                    case 7:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c007.jpg"))); break;

                    case 8:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c008.jpg"))); break;

                    case 9:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c009.jpg"))); break;

                    case 10:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c010.jpg"))); break;

                    case 11:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c011.jpg"))); break;

                    case 12:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c012.jpg"))); break;

                    case 13:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c013.jpg"))); break;

                    case 14:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c014.jpg"))); break;

                    case 15:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c015.jpg"))); break;

                    case 16:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c016.jpg"))); break;

                    case 17:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c017.gif"))); break;

                    case 18:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c018.jpg"))); break;

                    case 19:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c019.gif"))); break;

                    case 20:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c020.jpg"))); break;

                    case 21:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c021.gif"))); break;

                    case 22:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c022.jpg"))); break;

                    case 23:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c023.gif"))); break;

                    case 24:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c024.jpg"))); break;

                    case 25:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c025.jpg"))); break;

                    case 26:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c026.gif"))); break;

                    case 27:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c027.gif"))); break;

                    case 28:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c028.jpg"))); break;

                    case 29:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c029.jpg"))); break;

                    case 30:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c030.gif"))); break;

                    case 31:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c031.gif"))); break;

                    case 32:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c032.jpg"))); break;

                    case 33:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c033.jpg"))); break;

                    case 34:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c034.jpg"))); break;

                    case 35:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c035.jpg"))); break;

                    case 36:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c036.jpg"))); break;

                    case 37:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c037.jpg"))); break;

                    case 38:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c038.jpg"))); break;

                    case 39:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c039.jpg"))); break;

                    case 40:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c040.jpg"))); break;

                    case 41:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c041.jpg"))); break;

                    case 42:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c042.jpg"))); break;

                    case 43:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c043.jpg"))); break;

                    case 44:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c044.jpg"))); break;

                    case 45:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c045.jpg"))); break;

                    case 46:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c046.jpg"))); break;

                    case 47:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c047.jpg"))); break;

                    case 48:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c048.jpg"))); break;

                    case 49:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c049.jpg"))); break;

                    case 50:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c050.jpg"))); break;

                    case 51:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c051.jpg"))); break;

                    case 52:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c052.jpg"))); break;

                    case 53:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c053.jpg"))); break;

                    case 54:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c054.jpg"))); break;

                    case 55:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c055.jpg"))); break;

                    case 56:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c056.jpg"))); break;

                    case 57:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c057.jpg"))); break;

                    case 58:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c058.jpg"))); break;

                    case 59:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c059.jpg"))); break;

                    case 60:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c060.jpg"))); break;

                    case 61:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c061.jpg"))); break;

                    case 62:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c062.gif"))); break;

                    case 63:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c063.jpg"))); break;

                    case 64:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c064.gif"))); break;

                    case 65:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c065.jpg"))); break;

                    case 66:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c066.jpg"))); break;

                    case 67:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c067.jpg"))); break;

                    case 68:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c068.jpg"))); break;

                    case 69:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c069.jpg"))); break;

                    case 70:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c070.jpg"))); break;

                    case 71:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c071.jpg"))); break;

                    case 72:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c072.jpg"))); break;

                    case 73:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c073.gif"))); break;

                    case 74:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c074.jpg"))); break;

                    case 75:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c075.jpg"))); break;

                    case 76:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c076.jpg"))); break;

                    case 77:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c077.jpg"))); break;

                    case 78:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c078.jpg"))); break;

                    case 79:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c079.jpg"))); break;

                    case 80:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c080.jpg"))); break;

                    case 81:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c081.jpg"))); break;

                    case 82:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c082.jpg"))); break;

                    case 83:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c083.jpg"))); break;

                    case 84:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c084.jpg"))); break;

                    case 85:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c085.jpg"))); break;

                    case 86:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c086.jpg"))); break;

                    case 87:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c087.jpg"))); break;

                    case 88:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c088.jpg"))); break;

                    case 89:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c089.jpg"))); break;

                    case 90:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c090.jpg"))); break;

                    case 91:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c091.jpg"))); break;
                    case 92:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c092.jpg"))); break;

                    case 93:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c093.jpg"))); break;

                    case 94:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c094.jpg"))); break;

                    case 95:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c095.jpg"))); break;

                    case 96:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c096.jpg"))); break;

                    case 97:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c097.jpg"))); break;

                    case 98:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c098.jpg"))); break;

                    case 99:b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/character/c099.jpg"))); break;




                }


            } else {JOptionPane.showMessageDialog(this,"last reached");}
        } catch (Exception e){
        }
        try {
            String sql1 = "select used from charactar where id ='"+img1.getText()+"' ;";

            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s1 = con1.createStatement();
            ResultSet rs1 = null;

            rs1 = s1.executeQuery(sql1);
            rs1.next();

            String aa1 = null;

            aa1 = rs1.getString("used");


            if (aa1.equals("yes")){ifitis.setText(" in use");} else ifitis.setText("not in use");

            con1.close();
            s1.close();

        } catch (Exception e){JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void ifitisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifitisActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ifitisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(a1.getText().equals("")){JOptionPane.showMessageDialog(this,"Enter your Name");}else{
        int noofcards =10;




        String card="";
        String tr1="000";
        boolean mew = (9==9);
        try{
            String yy = "yugioh";

            String sql = "select nameid from "+ yy +";" ;//yy is tablename
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery(sql);
            while (rs.next()){
                String ab = rs.getString(1);
                String pto =""+ab,hbj="";
                if(pto.length()<2){hbj="00"+pto;} else if(pto.length()<3){hbj="0"+pto;} else if(pto.length()>2){hbj=""+pto;}
                String tyb =(""+hbj);
                card +=tyb;
            }//pro till here correct fffffggg
            con.close();
            s.close();
            rs.close();
        } catch (Exception e){JOptionPane.showMessageDialog(this, "select deck name");}

        int rt =card.length();

        for (int i=0;i<=noofcards;i+=1){



            int ra=(int)(Math.random()*51);

            String po =""+ra,hj="";
            if(po.length()<2){hj="00"+po;} else if(po.length()<3){hj="0"+po;} else if(po.length()>2){hj=""+po;}
            String ty =(""+hj);


            //introduce random variable;
            for (int jj=0;jj<tr1.length()-1;jj=jj+3){
                String sd1 =tr1.substring(jj, jj+3);    // JOptionPane.showMessageDialog(this, sd1+"##"+tr1+"##"+ty);
                mew =!(sd1.equalsIgnoreCase(""+ty));
                if (mew ==false)break;
            }
            if (mew){

                tr1+=ty;
                try{
                    String sql1 = "create table "+a1.getText()+"deck (cardid varchar(4));";

                    Class.forName("java.sql.Driver");
                    Connection con1= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
                    Statement s1 = con1.createStatement();
                    s1.executeUpdate(sql1);

                    String mysql= tt1.getText();
                    tt1.setText("");
                    tt1.append(mysql+"\n");

                    tt1.append(sql1 +"\n");

                    con1.close();
                    s1.close();

                } catch (Exception e){
                    String tr =""+e;
                }
                try{

                    String sql2 = "insert into "+a1.getText()+"deck values ('"+ty+"');";
                    Class.forName("java.sql.Driver");
                    Connection con1= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
                    Statement s1 = con1.createStatement();
                    s1.executeUpdate(sql2);
                                 
                    String mysql= tt1.getText();
                    tt1.setText("");
                    tt1.append(mysql+"\n");

                    tt1.append(sql2 +"\n");
                    con1.close();
                    s1.close();

                } catch (Exception e){JOptionPane.showMessageDialog(this, e);
                }


            }//if
            else{
                --i;
            }
        }
}

        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(a1.getText().equals("")|| a3.getText().equals("")){JOptionPane.showMessageDialog(this,"Enter your Details");}else{        String x=a1.getText() ;

        String x2 =a3.getText();

        String tr= ifitis.getText();
        String x3=a4.getText() ;
        String x4=img1.getText() ;
        if (!(x4.equals(""))){
            if(!(tr.equalsIgnoreCase(" in use"))){
                try{
                    Class.forName("java.sql.Driver");
                    Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
                    Statement s = con.createStatement();




                    String sql1 ="create table player (name char(100),password varchar(100),points decimal(30,10),totalmatches int,win int,lost int,deckname varchar(100), imageid varchar(30));";

                    String mysql= tt1.getText();
                    tt1.setText("");
                    tt1.append(mysql+"\n");

                    tt1.append(sql1 +"\n");

                    s.executeUpdate(sql1);
                    con.close();
                    s.close();

                } catch (Exception e){String kj =""+e;
                if (kj.length()>3){int y =3;}}









                try{
                    Class.forName("java.sql.Driver");
                    Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
                    Statement s = con.createStatement();




                    String sql2 ="insert into player values ('"+(x)+"','"+x2+"',"+x3+",0,0,0,'"+x+"deck','" +x4+"' );" ;
                    String mysql= tt1.getText();
                    tt1.setText("");
                    tt1.append(mysql+"\n");

                    tt1.append(sql2 +"\n");

                    s.executeUpdate(sql2);
                    con.close();
                    s.close();
                    a1.setText("");
                    a3.setText("");
                    a4.setText("");
                } catch (Exception e){JOptionPane.showMessageDialog(this, e);}

                try{

                    String sql2 = "update charactar set used = 'yes' where id ='"+x4+"';";
                    Class.forName("java.sql.Driver");
                    Connection con1= DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
                    Statement s1 = con1.createStatement();
                    s1.executeUpdate(sql2);

                    con1.close();
                    s1.close();

                } catch (Exception e){JOptionPane.showMessageDialog(this, e);
                }//try

            }//if
            else{JOptionPane.showMessageDialog(this, "image is already selected by some one");}

        } else{JOptionPane.showMessageDialog(this, "select your image");}
}// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_b12ActionPerformed

    private void top12334FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top12334FocusGained
 try {
            String sql1 = "select used from charactar where id ='"+img1.getText()+"' ;";


            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gaurav","root","");
            Statement s1 = con1.createStatement();
            ResultSet rs1 = s1.executeQuery(sql1);
            rs1.next();

            String aa1 = rs1.getString(1);

            if (aa1.equals("yes")){ifitis.setText(" in use");} else ifitis.setText("not in use");

            con1.close();
            s1.close();

        } catch (Exception e){JOptionPane.showMessageDialog(this, e);
        }         // TODO add your handling code here:
}//GEN-LAST:event_top12334FocusGained

    private void topFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_topFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_topFocusGained

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f5playerenroller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JPasswordField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JButton b12;
    private javax.swing.JToggleButton b2;
    private javax.swing.JButton ifitis;
    private javax.swing.JButton img1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel top;
    private javax.swing.JLabel top12334;
    private javax.swing.JTextArea tt1;
    // End of variables declaration//GEN-END:variables

}
